version: '3.8'

services:

  nginx:
    image: nginx:1.23-alpine
    container_name: web
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./public:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf
    networks:
      - sandbox-vuejs

networks:
  sandbox-vuejs:
